---
title: "Test3"
author: "Li Yao"
date: "6/30/2021"
output: html_document
---

```{r}
library(GOFEmpirical)
```


## Histogram of p-value
## CvM, Logistic

```{r}
check.CvM.logistic = function(par,n,m){
  out <- matrix(0,m,1)
  pval <- matrix(0,m,1)
  for(i in 1:m){
    x=rlogis(n,par[1],par[2])
    out[i,]=CvM.logistic(x)
    pval[i,]=CvM.logistic.pvalue(out[i,])$P
  }
  hist(out,main="CvM statistics for Logistic random sample")
  abline(v=mean(out), col="red")
  hist(pval,main="p value of CvM")
  abline(v=mean(pval), col="red")
}
system.time(check.CvM.logistic(c(2,1),400,200))
```


## Histogram of p-value
## CvM, Weibull

```{r}
check.CvM.weibull = function(par,n,m){
  out <- matrix(0,m,1)
  pval <- matrix(0,m,1)
  for(i in 1:m){
    x=rweibull(n,par[1],par[2])
    out[i,]=CvM.weibull(x)
    pval[i,]=CvM.weibull.pvalue(out[i,],verbose=TRUE)$P
  }
  hist(out,main="CvM statistics for Weibull random sample",breaks=50)
  abline(v=mean(out), col="red")
  hist(pval,main="p value of CvM")
  abline(v=mean(pval), col="red")
}
system.time(check.CvM.weibull(c(2,1),400,200))

```

